language: php
php:
  - 5.5
  - 7.1

services:
  - mysql

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS go7_test;' -uroot
  - mysql -e 'CREATE DATABASE go7_test;' -uroot

script: phpunit --configuration tests/phpunit.xml --coverage-text
