language: php
php:
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql

before_script:
  - cp tests/config.php.example tests/config.php
  - mysql -e 'DROP DATABASE IF EXISTS go7_test;' -uroot
  - mysql -e 'CREATE DATABASE go7_test;' -uroot
  - composer update

script: vendor/bin/phpunit --configuration tests/phpunit.xml

notifications:
  email:
    - kantoor@intermesh.nl