-- MySQL Script generated by MySQL Workbench
-- Tue 19 Apr 2016 04:24:20 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema groupoffice7
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `calendar_recurrence_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calendar_recurrence_rule` (
  `eventId` INT NOT NULL,
  `frequency` VARCHAR(10) NOT NULL,
  `until` DATETIME NULL,
  `occurrences` INT NULL,
  `interval` INT NOT NULL DEFAULT 0,
  `byDay` INT(11) NULL,
  `byMonth` INT(10) UNSIGNED NULL,
  `byYearday` BIGINT NULL,
  `byMonthday` BIGINT(20) UNSIGNED NULL,
  `byHour` BIGINT(20) NULL,
  `byMinute` BIGINT(20) NULL,
  `bySecond` BIGINT(20) NULL ,
  `bySetPos` BIGINT NOT NULL DEFAULT 0,
  `rrule` varchar(191) NOT NULL,
  PRIMARY KEY (`eventId`),
  INDEX `fk_calendar_recurrence_rule_calendar_event1_idx` (`eventId` ASC),
  CONSTRAINT `fk_calendar_recurrence_rule_calendar_event1`
    FOREIGN KEY (`eventId`)
    REFERENCES `calendar_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calendar_exception`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calendar_exception` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recurrenceEventId` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `recurrenceEventId`),
  INDEX `fk_calendar_exception_calendar_recurrence_rule1_idx` (`recurrenceEventId` ASC),
  CONSTRAINT `fk_calendar_exception_calendar_recurrence_rule1`
    FOREIGN KEY (`recurrenceEventId`)
    REFERENCES `calendar_recurrence_rule` (`eventId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calendar_calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calendar_calendar` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(191) NOT NULL,
  `color` CHAR(6) NULL,
  `version` INT NOT NULL DEFAULT 1,
  `ownedBy` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calendar_calendar_core_user1_idx` (`ownedBy` ASC),
  CONSTRAINT `fk_calendar_calendar_core_user1`
    FOREIGN KEY (`ownedBy`)
    REFERENCES `auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calendar_attending_individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calendar_attending_individual` (
  `eventId` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `role` TINYINT NOT NULL DEFAULT 1,
  `responseStatus` TINYINT NOT NULL DEFAULT 1,
  `calendarId` INT NULL,
  `userId` INT NULL,
  PRIMARY KEY (`eventId`, `email`),
  INDEX `fk_calendar_attendee_calendar_event1_idx` (`eventId` ASC),
  INDEX `fk_calendar_attending_user_core_user1_idx` (`userId` ASC),
  INDEX `fk_calendar_attendee_user_calendar_calendar1_idx` (`calendarId` ASC),
  CONSTRAINT `fk_calendar_attendee_calendar_event1`
    FOREIGN KEY (`eventId`)
    REFERENCES `calendar_event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_attending_user_core_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_attendee_user_calendar_calendar1`
    FOREIGN KEY (`calendarId`)
    REFERENCES `calendar_calendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calendar_event`
-- -----------------------------------------------------
CREATE TABLE `calendar_event` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(191) NOT NULL,
  `allDay` tinyint(1) NOT NULL DEFAULT '0',
  `startAt` datetime NOT NULL,
  `endAt` datetime NOT NULL,
  `createdAt` datetime NOT NULL,
  `modifiedAt` datetime NOT NULL,
  `title` varchar(191) NOT NULL,
  `description` text,
  `location` varchar(144)DEFAULT NULL,
  `vevent` text,
  `status` tinyint(4) NOT NULL DEFAULT '1',
  `tag` varchar(20) DEFAULT NULL,
  `visibility` tinyint(4) NOT NULL DEFAULT '1',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `exceptionId` int(11) DEFAULT NULL,
  `organizerEmail` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_calendar_event_calendar_exception1_idx` (`exceptionId`,`id`),
  KEY `fk_calendar_event_calendar_attending_individual1_idx` (`id`,`organizerEmail`),
  CONSTRAINT `fk_calendar_event_calendar_exception1` FOREIGN KEY (`exceptionId`, `id`)
	REFERENCES `calendar_exception` (`id`, `recurrenceEventId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB;



-- -----------------------------------------------------
-- Table `calendar_alarm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `calendar_alarm` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `trigger` varchar(28) DEFAULT NULL,
  `triggerAt` datetime NOT NULL,
  `relativeTo` int(11) NOT NULL DEFAULT '1',
  `eventId` int(11) NOT NULL,
  `userId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_calendar_alarm_calendar_attending_individual1_idx` (`eventId`),
  KEY `fk_calendar_alarm_auth_user_idx` (`userId`),
  CONSTRAINT `fk_calendar_alarm_auth_user` FOREIGN KEY (`userId`)
    REFERENCES `auth_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_alarm_calendar_attending_individual1` FOREIGN KEY (`eventId`)
	REFERENCES `calendar_attending_individual` (`eventId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `calendar_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calendar_resource` (
  `id` INT NOT NULL,
  `type` INT NOT NULL DEFAULT 1,
  `name` VARCHAR(100) NOT NULL,
  `autoAccept` TINYINT NOT NULL DEFAULT 1,
  `delegateId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calendar_resource_core_user1_idx` (`delegateId` ASC),
  CONSTRAINT `fk_calendar_resource_core_user1`
    FOREIGN KEY (`delegateId`)
    REFERENCES `auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calendar_event_attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calendar_event_attachment` (
  `eventId` INT NOT NULL,
  `blobId` CHAR(40) CHARACTER SET 'ascii' BINARY NOT NULL,
  `recurrenceId` DATETIME NULL,
  PRIMARY KEY (`eventId`, `blobId`),
  INDEX `fk_calendar_event_has_blob_blob1_idx` (`blobId` ASC),
  INDEX `fk_calendar_event_attachment_calendar_event1_idx` (`eventId` ASC),
  CONSTRAINT `fk_calendar_event_has_file_file_file_file1`
    FOREIGN KEY (`blobId`)
    REFERENCES `blob_blob` (`blobId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_event_attachment_calendar_event1`
    FOREIGN KEY (`eventId`)
    REFERENCES `calendar_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calendar_attending_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calendar_attending_resource` (
  `resourceId` INT NOT NULL,
  `eventId` INT NOT NULL,
  `role` TINYINT NOT NULL DEFAULT 1,
  `responseStatus` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`resourceId`, `eventId`),
  INDEX `fk_calendar_resource_has_calendar_event_calendar_event1_idx` (`eventId` ASC),
  INDEX `fk_calendar_resource_has_calendar_event_calendar_resource1_idx` (`resourceId` ASC),
  CONSTRAINT `fk_calendar_attendee_resource_calendar_resource1`
    FOREIGN KEY (`resourceId`)
    REFERENCES `calendar_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_attendee_resource_calendar_event1`
    FOREIGN KEY (`eventId`)
    REFERENCES `calendar_event` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calendar_default_alarm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calendar_default_alarm` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `trigger` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `relativeTo` int(11) NOT NULL DEFAULT '0',
  `calendarId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_calendar_default_alarm_calendar_calendar1_idx` (`calendarId`),
  CONSTRAINT `fk_calendar_default_alarm_calendar_calendar1` FOREIGN KEY (`calendarId`) REFERENCES `calendar_calendar` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS `calendar_event_attachment` (
  `eventId` INT NOT NULL,
  `blobId` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`eventId`, `blobId`),
  INDEX `fk_calendar_event_has_blob_blob1_idx` (`blobId` ASC),
  INDEX `fk_calendar_event_attachment_calendar_event1_idx` (`eventId` ASC),
  CONSTRAINT `fk_calendar_event_has_blob_blob1`
    FOREIGN KEY (`blobId`)
    REFERENCES `blob_blob` (`blobId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_event_attachment_calendar_event1`
    FOREIGN KEY (`eventId`)
    REFERENCES `calendar_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
